function gui = arrangeFreqRespTab(gui)

gui.freqRespU = uiextras.Grid('Parent',gui.frequencyResponse,'Spacing',5);
gui.freqRespD = uiextras.Grid('Parent',gui.frequencyResponse,'Spacing',5);
set(gui.frequencyResponse, 'Sizes', [8*32+15 -1]);

handle = uicontrol('Parent',gui.freqRespU, ...
    'Style','text', ...
    'FontSize',10,...
    'String','Input CH:');
javaHandle = findjobj(handle);
align(handle, 'None', 'Middle'); 
%javaHandle.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
handle = uicontrol('Parent',gui.freqRespU, ...
    'Style','text', ...
    'FontSize',10,...
    'String','Output CH+:');
javaHandle = findjobj(handle);
align(handle, 'None', 'Middle'); 
%javaHandle.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
handle = uicontrol('Parent',gui.freqRespU, ...
    'Style','text', ...
    'FontSize',10,...
    'String','Output CH-:');
javaHandle = findjobj(handle);
align(handle, 'None', 'Middle'); 
%javaHandle.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
uiextras.Empty('Parent', gui.freqRespU);
handle = uicontrol('Parent',gui.freqRespU, ...
    'Style','text', ...
    'FontSize',10,...
    'String','Start Frequency [Hz]:');
javaHandle = findjobj(handle);
align(handle, 'None', 'Middle'); 
%javaHandle.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
handle = uicontrol('Parent',gui.freqRespU, ...
    'Style','text', ...
    'FontSize',10,...
    'String','Stop Frequency [Hz]:');
javaHandle = findjobj(handle);
align(handle, 'None', 'Middle'); 
%javaHandle.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
handle = uicontrol('Parent',gui.freqRespU, ...
    'Style','text', ...
    'FontSize',10,...
    'String','Step Frequency [Hz]:');
javaHandle = findjobj(handle);
align(handle, 'None', 'Middle'); 
%javaHandle.setVerticalAlignment(javax.swing.SwingConstants.CENTER);

uiextras.Empty('Parent', gui.freqRespU);

gui.inputChannelFreqResp = uicontrol('Parent',gui.freqRespU, ...
    'Style','popupmenu', ...
    'String',{'CH1','CH2'},...
    'FontSize',10, ...
    'Callback',@onInputChannelFreqResp);
gui.outputChannelPFreqResp = uicontrol('Parent',gui.freqRespU, ...
    'Style','popupmenu', ...
    'String',{'CH1','CH2', 'CH3', 'CH4'},...
    'FontSize',10, ...
    'Callback',@onOutputChannelPFreqResp);
gui.outputChannelNFreqResp = uicontrol('Parent',gui.freqRespU, ...
    'Style','popupmenu', ...
    'String',{'CH1','CH2', 'CH3', 'CH4'},...
    'FontSize',10, ...
    'Value',2, ...
    'Enable','off',...
    'Callback',@onOutputChannelNFreqResp);
uiextras.Empty('Parent', gui.freqRespU);
gui.startF = uicontrol('Parent',gui.freqRespU, ...
    'Style','edit', ...
    'String','10000',...
    'Callback',@onStartF);
gui.stopF = uicontrol('Parent',gui.freqRespU, ...
    'Style','edit', ...
    'String','10000000',...
    'Callback',@onStopF);
gui.stepF = uicontrol('Parent',gui.freqRespU, ...
    'Style','edit', ...
    'String','10000',...
    'Callback',@onStepF);

uicontrol('Parent',gui.freqRespD, ...
    'Style','pushbutton',...
    'String','Measure Response',...
    'FontSize',10,...
    'Callback',@onMeasureFreqResp);
uiextras.Empty('Parent',gui.freqRespD);
uicontrol('Parent',gui.freqRespD, ...
    'Style','pushbutton',...
    'String','Plot Data',...
    'FontSize',10,...
    'Callback',@onPlotDataFreqResp);
uicontrol('Parent',gui.freqRespD, ...
    'Style','pushbutton',...
    'String','Save Data',...
    'FontSize',10,...
    'Callback',@onSaveDataFreqResp);


set(gui.freqRespU, 'ColumnSizes', [-1 -1], 'RowSizes', [32 32 32 32 32 32 32 32]);
set(gui.freqRespD, 'ColumnSizes', [-1 -1], 'RowSizes', [-1 -1]);
