function gui = arrangeMIMOPAMTab(gui)

gui.MIMOPAMU = uiextras.Grid('Parent',gui.MIMOPAM,'Spacing',5);
gui.MIMOPAMD = uiextras.Grid('Parent',gui.MIMOPAM,'Spacing',5);
set(gui.MIMOPAM, 'Sizes', [7*32 + 20 -1]);


handle = uicontrol('Parent',gui.MIMOPAMU, ...
    'Style','text', ...
    'FontSize',10,...
    'String','Input CH1:');
javaHandle = findjobj(handle);
align(handle, 'None', 'Middle'); 
%javaHandle.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
handle = uicontrol('Parent',gui.MIMOPAMU, ...
    'Style','text', ...
    'FontSize',10,...
    'String','Input CH2:');
javaHandle = findjobj(handle);
align(handle, 'None', 'Middle'); 
%javaHandle.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
handle = uicontrol('Parent',gui.MIMOPAMU, ...
    'Style','text', ...
    'FontSize',10,...
    'String','Output CH1:');
javaHandle = findjobj(handle);
align(handle, 'None', 'Middle'); 
%javaHandle.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
handle = uicontrol('Parent',gui.MIMOPAMU, ...
    'Style','text', ...
    'FontSize',10,...
    'String','Output CH2:');
javaHandle = findjobj(handle);
align(handle, 'None', 'Middle'); 
%javaHandle.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
uiextras.Empty('Parent', gui.MIMOPAMU);

handle = uicontrol('Parent',gui.MIMOPAMU, ...
    'Style','text', ...
    'FontSize',10,...
    'String','Max. Modulation Order:');
javaHandle = findjobj(handle);
align(handle, 'None', 'Middle'); 
%javaHandle.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
% handle = uicontrol('Parent',gui.MIMOPAMU, ...
%     'Style','text', ...
%     'FontSize',10,...
%     'String','Adaptive Threshold:');
% javaHandle = findjobj(handle);
% javaHandle.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
uiextras.Empty('Parent', gui.MIMOPAMU);

gui.outputChannel1PMIMOPAM = uicontrol('Parent',gui.MIMOPAMU, ...
    'Style','popupmenu', ...
    'String',{'CH1','CH2','CH3','CH4','FN1','FN2'},...
    'FontSize',10, ...
    'Callback',@onOutputChannel1PMIMOPAM);
gui.outputChannel1NMIMOPAM = uicontrol('Parent',gui.MIMOPAMU, ...
    'Style','popupmenu', ...
    'String',{'CH1','CH2','CH3','CH4','FN1','FN2'},...
    'FontSize',10, ...
    'Value',2, ...
    'Enable','off', ...
    'Callback',@onOutputChannel1NMIMOPAM);
gui.outputChannel2PMIMOPAM = uicontrol('Parent',gui.MIMOPAMU, ...
    'Style','popupmenu', ...
    'String',{'CH1','CH2','CH3','CH4','FN1','FN2'},...
    'FontSize',10, ...
    'Value',3, ...
    'Callback',@onOutputChannel2PMIMOPAM);
gui.outputChannel2NMIMOPAM = uicontrol('Parent',gui.MIMOPAMU, ...
    'Style','popupmenu', ...
    'String',{'CH1','CH2','CH3','CH4','FN1','FN2'},...
    'FontSize',10, ...
    'Value',4, ...
    'Enable','off', ...
    'Callback',@onOutputChannel2NMIMOPAM);
uiextras.Empty('Parent', gui.MIMOPAMU);

gui.maxConstellationSizeMIMOPAM = uicontrol('Parent', gui.MIMOPAMU, ...
    'Style', 'popupmenu', ...
    'FontSize', 10, ...
    'String',{'2','4','8','16','32','64','128','256','512','1024'}, ... 
    'Callback',@onMaxConstellationMIMOPAM);
% gui.adaptiveThresholdMIMOPAM = uicontrol('Parent', gui.MIMOPAMU, ...
%     'Style', 'checkbox', ...
%     'Callback', @onAdaptiveThresholdMIMOPAM);
uiextras.Empty('Parent', gui.MIMOPAMU);

uicontrol('Parent',gui.MIMOPAMD, ...
    'Style','pushbutton',...
    'String','Generate Signal',...
    'FontSize',10,...
    'Callback',@onGenerateSignalMIMOPAM);
uicontrol('Parent',gui.MIMOPAMD, ...
    'Style','pushbutton',...
    'String','Capture & Demodulate Signal',...
    'FontSize',10,...
    'Callback',@onCaptureDemodulateSignalMIMOPAM);
uicontrol('Parent',gui.MIMOPAMD, ...
    'Style','pushbutton',...
    'String','Plot Data',...
    'FontSize',10,...
    'Callback',@onPlotDataMIMOPAM);
uicontrol('Parent',gui.MIMOPAMD, ...
    'Style','pushbutton',...
    'String','Save Data',...
    'FontSize',10,...
    'Callback',@onSaveDataMIMOPAM);


set(gui.MIMOPAMU, 'ColumnSizes', [-1 -1], 'RowSizes', [32 32 32 32 32 32 32]);
set(gui.MIMOPAMD, 'ColumnSizes', [-1 -1], 'RowSizes', [-1 -1]);