function gui = arrangeSISOPAMTab(gui)

gui.SISOPAMU = uiextras.Grid('Parent',gui.SISOPAM,'Spacing',5);
gui.SISOPAMD = uiextras.Grid('Parent',gui.SISOPAM,'Spacing',5);
set(gui.SISOPAM, 'Sizes', [6*32 + 20 -1]);


handle = uicontrol('Parent',gui.SISOPAMU, ...
    'Style','text', ...
    'FontSize',10,...
    'String','Input CH:');
javaHandle = findjobj(handle);
align(handle, 'None', 'Middle'); 
%javaHandle.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
handle = uicontrol('Parent',gui.SISOPAMU, ...
    'Style','text', ...
    'FontSize',10,...
    'String','Output CH+:');
javaHandle = findjobj(handle);
align(handle, 'None', 'Middle'); 
%javaHandle.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
handle = uicontrol('Parent',gui.SISOPAMU, ...
    'Style','text', ...
    'FontSize',10,...
    'String','Output CH-:');
javaHandle = findjobj(handle);
align(handle, 'None', 'Middle'); 
%javaHandle.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
uiextras.Empty('Parent', gui.SISOPAMU);

handle = uicontrol('Parent',gui.SISOPAMU, ...
    'Style','text', ...
    'FontSize',10,...
    'String','Max. Modulation Order:');
javaHandle = findjobj(handle);
align(handle, 'None', 'Middle'); 
%javaHandle.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
% handle = uicontrol('Parent',gui.SISOPAMU, ...
%     'Style','text', ...
%     'FontSize',10,...
%     'String','Adaptive Threshold:');
% javaHandle = findjobj(handle);
% javaHandle.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
uiextras.Empty('Parent', gui.SISOPAMU);

gui.inputChannelSISOPAM = uicontrol('Parent',gui.SISOPAMU, ...
    'Style','popupmenu', ...
    'String',{'CH1','CH2', 'CH1+CH2'},...
    'FontSize',10, ...
    'Callback',@onInputChannelSISOPAM);
gui.outputChannelPSISOPAM = uicontrol('Parent',gui.SISOPAMU, ...
    'Style','popupmenu', ...
    'String',{'CH1','CH2','CH3','CH4','FN1'},...
    'FontSize',10, ...
    'Callback',@onOutputChannelPSISOPAM);
gui.outputChannelNSISOPAM = uicontrol('Parent',gui.SISOPAMU, ...
    'Style','popupmenu', ...
    'String',{'CH1','CH2','CH3','CH4'},...
    'FontSize',10, ...
    'Value',2, ...
    'Enable','off', ...
    'Callback',@onOutputChannelNSISOPAM);
uiextras.Empty('Parent', gui.SISOPAMU);
gui.maxConstellationSizeSISOPAM = uicontrol('Parent', gui.SISOPAMU, ...
    'Style', 'popupmenu', ...
    'FontSize', 10, ...
    'String',{'2','4','8','16','32','64','128','256','512','1024'}, ... 
    'Callback',@onMaxConstellationSISOPAM);
% gui.adaptiveThresholdSISOPAM = uicontrol('Parent', gui.SISOPAMU, ...
%     'Style', 'checkbox', ...
%     'Callback', @onAdaptiveThresholdSISOPAM);
uiextras.Empty('Parent', gui.SISOPAMU);

uicontrol('Parent',gui.SISOPAMD, ...
    'Style','pushbutton',...
    'String','Generate Signal',...
    'FontSize',10,...
    'Callback',@onGenerateSignalSISOPAM);
uicontrol('Parent',gui.SISOPAMD, ...
    'Style','pushbutton',...
    'String','Capture & Demodulate Signal',...
    'FontSize',10,...
    'Callback',@onCaptureDemodulateSignalSISOPAM);
uicontrol('Parent',gui.SISOPAMD, ...
    'Style','pushbutton',...
    'String','Plot Data',...
    'FontSize',10,...
    'Callback',@onPlotDataSISOPAM);
uicontrol('Parent',gui.SISOPAMD, ...
    'Style','pushbutton',...
    'String','Save Data',...
    'FontSize',10,...
    'Callback',@onSaveDataSISOPAM);


set(gui.SISOPAMU, 'ColumnSizes', [-1 -1], 'RowSizes', [32 32 32 32 32 32]);
set(gui.SISOPAMD, 'ColumnSizes', [-1 -1], 'RowSizes', [-1 -1]);